### ISSUE TITLE
Does this prompt from the NuGet Package Manager have any impact?

### ISSUE THREAD

**Issue by yangf85** [datahint-eu/vizor-echarts#18]
![image](https://github.com/datahint-eu/vizor-echarts/assets/42733580/ca97bf32-d7f2-45ab-83c2-6109b0c0ae9d)

thank you~

**Comment by bmotmans** [comment]
Fixed in [https://github.com/datahint-eu/vizor-echarts/commit/bbb65ce254779b0983a7f47f3b436df504c3d940](this commit)
