### ISSUE TITLE
Getting access to the selected item

### ISSUE THREAD

**Issue by danielcooper-hk** [datahint-eu/vizor-echarts#21]
Hello,

Very impressed so far with the library so far.  I am trying to get off Syncfusion from a speed and cost perspective and Echarts is great and given my experience with Javascript having a wrapper library is perfect for me.

One of my use cases, requires me to update a separate chart when a segment of a pie chart is selected.  I've got the selection part working but I cannot seem to find how to either capture the selection event or access a list of selected items.

My pie series configuration is :

```
options.Series = new()
{ 
    new PieSeries()
    {
        Name = SeriesName,
        Radius = IsDoughtnut ? new CircleRadius("40%", "70%") : new CircleRadius("50%"),
        AvoidLabelOverlap = true,
        StillShowZeroSum = false,
        ShowEmptyCircle = false,
        SelectedMode = AllowSingleSelection ? Vizor.ECharts.SelectionMode.Single : null,
        SelectedOffset = 20, 
        Data = Data,
        Label = new()
        {
             Show = true, 
             Overflow = Overflow.Truncate,
             Precision = 2,
             Formatter = "{b}: {d}%"
        },
        LabelLine = new()
        {
            Show = true,
        },
        ItemStyle = new()
            {
                BorderRadius = 10,
                BorderColor = "#fff",
                BorderWidth= 2
            },
        Emphasis = new()
        {
            ItemStyle = new()
            {
                ShadowBlur = 10,
                ShadowOffsetX = 0,

                ShadowColor = Vizor.ECharts.Color.FromRGBA(0, 0, 0, 0.5)
            }
        }
    }
}; 
```

If anyone has any ideas it would be great to hear from you.

**Comment by bmotmans** [comment]
I added support for echarts EventParams.


You can now add a OnChartClick eventcallback.
`<Vizor.ECharts.EChart ... OnChartClick="OnChartClick"/>`

Which gives you access to the series index, data index, name, ... .

Sample in the demo app (Misc > Selection) or [full source code here](https://github.com/datahint-eu/vizor-echarts/blob/main/src/Vizor.ECharts.Samples/Areas/Misc/SelectionPieChart.razor)
![image](https://github.com/datahint-eu/vizor-echarts/assets/261057/6aaf5e8a-1b6e-4aa0-a60e-fd523ece04fc)

A new version will be released soon.

**Comment by danielcooper-hk** [comment]
Amazing - thank you
