### ISSUE TITLE
How to disable a series by default?

### ISSUE THREAD

**Issue by chrnoe** [datahint-eu/vizor-echarts#22]
I want to set a series disabled by default, so that the user has to clicked on the legend entry to show its data in the chart. I don't found a option for. I think, the `_echart.Options.Legend.Selected` property is for that, but the class `Selected()` seems to have no parameters nor methods to work with. Is there a working approach to set a series disabeld by default?

**Comment by bmotmans** [comment]
In the next version (probably by the end of the week), you can do the following:
```
Legend = new()
{
	Data = new string[] { "Email", "Union Ads", "Video Ads", "Direct", "Search Engine" },
	Selected = new Selected()
	{
		{ "Union Ads", false },
		{ "Video Ads", false },
	}
}
```


Full example in the demo app (Misc > Selection) or [see source code](https://github.com/datahint-eu/vizor-echarts/blob/main/src/Vizor.ECharts.Samples/Areas/Misc/SelectionLineChart.razor)

**Comment by chrnoe** [comment]
@bmotmans , when will the new version be public?

**Comment by chrnoe** [comment]
Still waiting ... for a new version or a response at least.
Dear @bmotmans, if it's not possible to solve my issue in the next time, then let me know please, so I can try another solution for my problem. Thank you.
